---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "node-hn-app"
  namespace: "default"
  labels:
    app: "node-hn-app"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "node-hn-app"
  template:
    metadata:
      labels:
        app: "node-hn-app"
    spec:
      containers:
      - name: "node-hn-app"
        image: "acmereg.azurecr.io/node-hn-app:IMAGE_TAG"
        imagePullPolicy: "Always"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "node-hn-app-hpa"
  namespace: "default"
  labels:
    app: "node-hn-app"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "node-hn-app"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "node-hn-app-service"
  namespace: "default"
  labels:
    app: "node-hn-app"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 3000
  selector:
    app: "node-hn-app"
  type: "LoadBalancer"
