resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    condition: succeeded()
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: buildAndPush
        repository: 'node-hn-app'
        containerRegistry: 'acmereg'
        dockerfile: '**/Dockerfile'
        tags: |
          latest
          $(tag)

- stage: Deploy
  displayName: Deploy to Kubernetes
  jobs:
  - job: Deploy
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    steps:
    - task: Bash@3
      inputs:
        targetType: inline
        script: 'sed -i "s/IMAGE_TAG/$(tag)/" acme-kube.yaml'
    - task: Kubernetes@1
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscriptionEndpoint: 'acme-resource-manager'
        azureResourceGroup: 'AcmeCICD'
        kubernetesCluster: 'hn-app-demo'
        command: 'apply'
        arguments: '-f acme-kube.yaml'
        secretType: 'dockerRegistry'
        containerRegistryType: 'Azure Container Registry'
