resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Test
  displayName: Test Image
  jobs:
  - job: Test
    steps:
    - task: Npm@1
      inputs:
        command: 'install'
    - task: Npm@1
      inputs:
        command: 'custom'
        customCommand: 'test'

- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    condition: succeeded()
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: buildAndPush
        repository: 'node-hn-app'
        containerRegistry: 'acmereg'
        dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
