---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "node-hn-app-service"
  namespace: "default"
  labels:
    app: "node-hn-app"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 3000
  selector:
    app: "node-hn-app"
  type: "LoadBalancer"